name: asistan_proje
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.5.1
  cupertino_icons: ^1.0.8
  #dart_openai: ^1.6.0  # OpenAI API için burda http için 0.13.2 sürümü gerekli unutma
  mysql1: ^0.20.0      # MySQL bağlantısı için
  firebase_auth: ^4.20.0 # Firebase Authentication (isteğe bağlı)
  cloud_firestore: ^4.15.0 # Firebase Firestore (isteğe bağlı)
  google_ml_kit: ^0.8.0
  #google_mlkit: ^0.17.0 
  firebase_core: ^2.24.2 # En son sürümü belirtin
  flutter_dotenv: ^5.1.0 
  http: ^1.1.0
  logger: ^2.5.0
  url_launcher: ^6.1.14
  intl: ^0.19.0
 # latest_version yerine en son sürümü yazın

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
